AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  SecurityGroupIds: 
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security Group IDs that Lambda will use
  VpcSubnetIds: 
      Type: List<AWS::EC2::Subnet::Id>
      Description: VPC Subnet IDs that Lambda will use (min 2 for HA)
  LambdaRoleId: 
    Type: AWS::IAM::Role::Id
    Description: Role for serverless function to use

Metadata:
  AWS::ServerlessRepo::Application:
    Name: the-illimination-game-api
    Description: The Illimination Game Api
    Author: Maisie Sadler
    SourceCodeUrl: https://github.com/maisiesadler/TheIlliminationGameApi
    ReadmeUrl: README.md

Resources:
  IlliminationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'OPTIONS,POST,GET,PUT,DELETE'"
        AllowOrigin: "'*'"
  testget:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/test/
      Handler: /get
      Runtime: go1.x
      Tracing: Active
      Role: !Ref LambdaRoleId
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IlliminationApi
            Path: /test
            Method: get
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref VpcSubnetIds