AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  SecurityGroupIds: 
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security Group IDs that Lambda will use
  VpcSubnetIds: 
      Type: List<AWS::EC2::Subnet::Id>
      Description: VPC Subnet IDs that Lambda will use (min 2 for HA)
  LambdaRoleArn:
    Type: String
    Description: Role arn for serverless function to use
  CognitoAuthorizerArn:
    Type: String
    Description: User pool arn to be used for auth

Metadata:
  AWS::ServerlessRepo::Application:
    Name: the-illimination-game-api
    Description: The Illimination Game Api
    Author: Maisie Sadler
    SourceCodeUrl: https://github.com/maisiesadler/TheIlliminationGameApi
    ReadmeUrl: README.md

Resources:
  IlliminationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'OPTIONS,POST,GET,PUT,DELETE'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref CognitoAuthorizerArn
  setupget:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/setup/
      Handler: /get
      Runtime: go1.x
      Tracing: Active
      Role: !Ref LambdaRoleArn
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IlliminationApi
            Path: /setup
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref VpcSubnetIds
  setuppidget:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/setup/p_id/
      Handler: /get
      Runtime: go1.x
      Tracing: Active
      Role: !Ref LambdaRoleArn
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IlliminationApi
            Path: /setup/{id}
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref VpcSubnetIds
  setuppidpost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/setup/p_id/
      Handler: /post
      Runtime: go1.x
      Tracing: Active
      Role: !Ref LambdaRoleArn
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IlliminationApi
            Path: /setup/{id}
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref VpcSubnetIds
  setupput:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/setup/
      Handler: /put
      Runtime: go1.x
      Tracing: Active
      Role: !Ref LambdaRoleArn
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IlliminationApi
            Path: /setup
            Method: put
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref VpcSubnetIds
  userget:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/user/
      Handler: /get
      Runtime: go1.x
      Tracing: Active
      Role: !Ref LambdaRoleArn
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IlliminationApi
            Path: /user
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref VpcSubnetIds
  userpost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/user/
      Handler: /post
      Runtime: go1.x
      Tracing: Active
      Role: !Ref LambdaRoleArn
      Events:
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref IlliminationApi
            Path: /user
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer
      Policies:
        - VPCAccessPolicy: {}
        # This policy gives permission for Lambdas to create/manage ENIs
        # SAM Policy templates you can use: https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/policy_templates/all_policy_templates.yaml
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref VpcSubnetIds